default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: gotta_be_stong_development

test:
  <<: *default
  database: gotta_be_strong_test

production:
  <<: *default
  database: gotta_be_strong_production
  # username: flixter
  # password: <%= ENV['FLIXTER_DATABASE_PASSWORD'] %>